import { StyleSheet } from "react-native";

import { displayFontFamily } from "../../src/theme/typography";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    minHeight: 0,
    backgroundColor: "#f7ecd9",
  },
  header: {
    alignItems: "center",
    backgroundColor: "#c9502e",
    flexDirection: "row",
    justifyContent: "space-between",
    paddingBottom: 28,
    paddingHorizontal: 24,
    paddingTop: 22,
  },
  headerCopy: {
    justifyContent: "center",
  },
  greeting: {
    color: "#ffd7c7",
    fontSize: 15,
  },
  name: {
    color: "#fff8ea",
    fontFamily: displayFontFamily,
    fontSize: 30,
    fontWeight: "600",
    marginTop: 2,
  },
  avatar: {
    alignItems: "center",
    backgroundColor: "#eba325",
    borderRadius: 16,
    height: 52,
    justifyContent: "center",
    width: 52,
  },
  menuBackdrop: {
    flex: 1,
  },
  accountMenu: {
    backgroundColor: "#fdf8ee",
    borderRadius: 20,
    minWidth: 200,
    paddingHorizontal: 18,
    paddingVertical: 14,
    position: "absolute",
    shadowColor: "#3a2317",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.18,
    shadowRadius: 16,
    elevation: 6,
  },
  accountName: {
    color: "#3a2317",
    fontSize: 16,
    fontWeight: "600",
  },
  accountEmail: {
    color: "#a68a6c",
    fontSize: 13,
    marginTop: 2,
  },
  accountDivider: {
    backgroundColor: "#ecdec2",
    height: 1,
    marginVertical: 12,
  },
  logoutRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
  },
  logoutText: {
    color: "#c9502e",
    fontSize: 15,
    fontWeight: "600",
  },
  avatarText: {
    color: "#3a1a0e",
    fontSize: 20,
    fontWeight: "600",
  },
  list: {
    flex: 1,
    minHeight: 0,
  },
  listContent: {
    backgroundColor: "#f7ecd9",
    flexGrow: 1,
    paddingBottom: 12,
    paddingHorizontal: 20,
    paddingTop: 22,
  },
  listHeaderRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  sectionTitle: {
    color: "#3a2317",
    fontFamily: displayFontFamily,
    fontSize: 23,
    fontWeight: "600",
  },
  sectionCount: {
    color: "#a68a6c",
    fontSize: 14,
  },
  card: {
    backgroundColor: "#fdf8ee",
    borderRadius: 22,
    marginBottom: 16,
    padding: 18,
    shadowColor: "#3a2317",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 2,
  },
  cardTopRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
  },
  tripName: {
    color: "#3a2317",
    flexShrink: 1,
    fontFamily: displayFontFamily,
    fontSize: 18,
    fontWeight: "600",
  },
  cardTopActions: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
  },
  weatherPill: {
    alignItems: "center",
    backgroundColor: "#f3ddb9",
    borderRadius: 999,
    flexDirection: "row",
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  weatherText: {
    color: "#c9502e",
    fontSize: 13,
    fontWeight: "600",
  },
  deleteButton: {
    alignItems: "center",
    backgroundColor: "#f3ddb9",
    borderRadius: 999,
    height: 32,
    justifyContent: "center",
    width: 32,
  },
  tripLocation: {
    color: "#a68a6c",
    fontSize: 14,
    marginTop: 6,
  },
  cardBottomRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 16,
  },
  dateRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 6,
  },
  dateText: {
    color: "#3a2317",
    fontSize: 14,
    fontWeight: "600",
  },
  statusRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 6,
  },
  statusText: {
    color: "#a68a6c",
    fontSize: 13,
  },
  addTripPrompt: {
    alignItems: "center",
    borderColor: "#e3c9a0",
    borderRadius: 22,
    borderStyle: "dashed",
    borderWidth: 1.5,
    flexDirection: "row",
    gap: 14,
    marginTop: 4,
    padding: 18,
  },
  addTripPromptText: {
    color: "#a68a6c",
    flex: 1,
    fontSize: 14,
    lineHeight: 20,
  },
  footer: {
    backgroundColor: "#f7ecd9",
    paddingBottom: 12,
    paddingHorizontal: 20,
    paddingTop: 4,
  },
  createButton: {
    alignItems: "center",
    backgroundColor: "#c9502e",
    borderRadius: 24,
    flexDirection: "row",
    gap: 10,
    height: 58,
    justifyContent: "center",
  },
  createButtonPressed: {
    backgroundColor: "#b5452a",
  },
  createButtonText: {
    color: "#fff8ea",
    fontSize: 18,
    fontWeight: "600",
  },
  confirmBackdrop: {
    backgroundColor: "rgba(58,35,23,0.45)",
    flex: 1,
    justifyContent: "flex-end",
  },
  confirmSheet: {
    backgroundColor: "#fdf8ee",
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    paddingHorizontal: 24,
    paddingTop: 24,
  },
  confirmIconWrap: {
    alignItems: "center",
    backgroundColor: "#f3ddb9",
    borderRadius: 16,
    height: 48,
    justifyContent: "center",
    width: 48,
  },
  confirmTitle: {
    color: "#3a2317",
    fontFamily: displayFontFamily,
    fontSize: 22,
    fontWeight: "600",
    marginTop: 18,
  },
  confirmMessage: {
    color: "#a68a6c",
    fontSize: 15,
    lineHeight: 21,
    marginTop: 10,
  },
  confirmActions: {
    flexDirection: "row",
    gap: 12,
    marginTop: 24,
  },
  cancelButton: {
    alignItems: "center",
    borderColor: "#e3c9a0",
    borderRadius: 20,
    borderWidth: 1.5,
    flex: 1,
    height: 54,
    justifyContent: "center",
  },
  cancelButtonText: {
    color: "#3a2317",
    fontSize: 16,
    fontWeight: "600",
  },
  deleteConfirmButton: {
    alignItems: "center",
    backgroundColor: "#c9502e",
    borderRadius: 20,
    flex: 1,
    height: 54,
    justifyContent: "center",
  },
  deleteConfirmButtonText: {
    color: "#fff8ea",
    fontSize: 16,
    fontWeight: "600",
  },
});
