import { StyleSheet } from "react-native";

import { displayFontFamily } from "../../src/theme/typography";

export const styles = StyleSheet.create({
  safeArea: {
    backgroundColor: "#f7ecd9",
    flex: 1,
    minHeight: 0,
  },
  topRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 14,
    paddingHorizontal: 20,
    paddingTop: 12,
  },
  backButton: {
    alignItems: "center",
    backgroundColor: "#fdf8ee",
    borderRadius: 16,
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  progressRow: {
    flex: 1,
    flexDirection: "row",
    gap: 8,
  },
  progressSegment: {
    backgroundColor: "#ecdcc0",
    borderRadius: 999,
    flex: 1,
    height: 5,
  },
  progressSegmentActive: {
    backgroundColor: "#c9502e",
  },
  scrollView: {
    flex: 1,
    minHeight: 0,
  },
  scrollContent: {
    paddingBottom: 24,
    paddingHorizontal: 20,
  },
  stepLabel: {
    color: "#d98a3d",
    fontSize: 13,
    fontWeight: "600",
    letterSpacing: 1.2,
    marginTop: 22,
    textTransform: "uppercase",
  },
  title: {
    color: "#2d1b12",
    fontFamily: displayFontFamily,
    fontSize: 30,
    fontWeight: "600",
    marginTop: 6,
  },
  noticeCard: {
    alignItems: "center",
    backgroundColor: "#fdf8ee",
    borderColor: "#ecd7b4",
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: "row",
    gap: 10,
    marginTop: 26,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  noticeText: {
    color: "#8b7a65",
    flex: 1,
    fontSize: 15,
  },
  heroWeatherCard: {
    backgroundColor: "#c9502e",
    borderRadius: 22,
    marginTop: 24,
    padding: 24,
  },
  heroWeatherTop: {
    alignItems: "flex-start",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  locationText: {
    color: "#ffd9c8",
    fontSize: 20,
  },
  currentTemp: {
    color: "#fff8ea",
    fontFamily: displayFontFamily,
    fontSize: 72,
    fontWeight: "600",
    lineHeight: 86,
    marginTop: 10,
  },
  feelsText: {
    color: "#ffd9c8",
    fontSize: 18,
    marginTop: 10,
  },
  weatherStatsRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 26,
  },
  weatherStat: {
    backgroundColor: "rgba(255, 248, 234, 0.18)",
    borderRadius: 16,
    flex: 1,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  weatherStatLabel: {
    color: "#ffd9c8",
    fontSize: 14,
  },
  weatherStatValue: {
    color: "#fff8ea",
    fontSize: 22,
    fontWeight: "600",
    marginTop: 6,
  },
  sectionLabel: {
    color: "#8b7a65",
    fontSize: 18,
    fontWeight: "600",
    letterSpacing: 1,
    marginTop: 28,
    textTransform: "uppercase",
  },
  forecastScroller: {
    marginHorizontal: -20,
    marginTop: 14,
  },
  forecastContent: {
    gap: 12,
    paddingHorizontal: 20,
  },
  dayCard: {
    alignItems: "center",
    backgroundColor: "#fdf8ee",
    borderColor: "#ecd7b4",
    borderRadius: 18,
    borderWidth: 1,
    minHeight: 148,
    paddingHorizontal: 16,
    paddingVertical: 14,
    width: 86,
  },
  dayAlertDot: {
    backgroundColor: "#e59525",
    borderRadius: 999,
    height: 10,
    position: "absolute",
    right: 14,
    top: 12,
    width: 10,
  },
  dayName: {
    color: "#2d1b12",
    fontSize: 16,
    fontWeight: "600",
  },
  dayDate: {
    color: "#a68a6c",
    fontSize: 14,
    marginTop: 2,
  },
  dayIcon: {
    marginTop: 16,
  },
  dayHigh: {
    color: "#2d1b12",
    fontSize: 18,
    fontWeight: "600",
    marginTop: 12,
  },
  dayLow: {
    color: "#a68a6c",
    fontSize: 17,
    marginTop: 2,
  },
  extrasCard: {
    alignItems: "flex-start",
    backgroundColor: "#f5e3bf",
    borderColor: "#eccd8d",
    borderRadius: 22,
    borderWidth: 1,
    flexDirection: "row",
    gap: 14,
    marginTop: 28,
    padding: 20,
  },
  extrasCopy: {
    flex: 1,
  },
  extrasTitle: {
    color: "#5b421b",
    fontSize: 20,
    fontWeight: "600",
  },
  extrasText: {
    color: "#916520",
    fontSize: 17,
    lineHeight: 25,
    marginTop: 8,
  },
  footer: {
    backgroundColor: "#f7ecd9",
    paddingBottom: 12,
    paddingHorizontal: 20,
    paddingTop: 12,
  },
  buildButton: {
    alignItems: "center",
    backgroundColor: "#c9502e",
    borderRadius: 24,
    flexDirection: "row",
    gap: 12,
    height: 64,
    justifyContent: "center",
  },
  buildButtonPressed: {
    backgroundColor: "#b5452a",
  },
  buildButtonText: {
    color: "#fff8ea",
    fontSize: 20,
    fontWeight: "600",
  },
});
