import { StyleSheet } from "react-native";

import { displayFontFamily } from "../../src/theme/typography";

export const styles = StyleSheet.create({
  safeArea: {
    backgroundColor: "#f7ecd9",
    flex: 1,
    minHeight: 0,
  },
  topRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 14,
    paddingHorizontal: 20,
    paddingTop: 12,
  },
  backButton: {
    alignItems: "center",
    backgroundColor: "#fdf8ee",
    borderRadius: 16,
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  progressRow: {
    flex: 1,
    flexDirection: "row",
    gap: 8,
  },
  progressSegment: {
    backgroundColor: "#ecdcc0",
    borderRadius: 999,
    flex: 1,
    height: 5,
  },
  progressSegmentActive: {
    backgroundColor: "#c9502e",
  },
  keyboardAvoiding: {
    flex: 1,
    minHeight: 0,
  },
  scrollView: {
    flex: 1,
    minHeight: 0,
  },
  scrollContent: {
    paddingBottom: 12,
    paddingHorizontal: 20,
  },
  stepLabel: {
    color: "#d98a3d",
    fontSize: 13,
    fontWeight: "600",
    letterSpacing: 1.2,
    marginTop: 22,
    textTransform: "uppercase",
  },
  title: {
    color: "#2d1b12",
    fontFamily: displayFontFamily,
    fontSize: 30,
    fontWeight: "600",
    marginTop: 6,
  },
  newStopCard: {
    backgroundColor: "#fdf8ee",
    borderColor: "#c9502e",
    borderRadius: 22,
    borderWidth: 2,
    marginTop: 24,
    padding: 18,
  },
  newStopLabel: {
    color: "#c9502e",
    fontSize: 13,
    fontWeight: "600",
    letterSpacing: 1.2,
    textTransform: "uppercase",
  },
  fieldLabel: {
    color: "#a68a6c",
    fontSize: 12,
    fontWeight: "600",
    letterSpacing: 1,
    marginTop: 14,
    textTransform: "uppercase",
  },
  cityInput: {
    borderColor: "#e3c9a0",
    borderRadius: 16,
    borderWidth: 1,
    color: "#2d1b12",
    fontSize: 16,
    marginTop: 6,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  locationMessageSlot: {
    justifyContent: "center",
    minHeight: 28,
  },
  locationError: {
    color: "#c9502e",
    fontSize: 13,
    fontWeight: "600",
    lineHeight: 18,
    marginTop: 8,
  },
  dateRow: {
    flexDirection: "row",
    gap: 12,
  },
  dateField: {
    flex: 1,
  },
  dateInputRow: {
    alignItems: "center",
    borderColor: "#e3c9a0",
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: "row",
    gap: 6,
    marginTop: 6,
    paddingHorizontal: 10,
    paddingVertical: 12,
  },
  dateValueText: {
    color: "#2d1b12",
    flex: 1,
    fontSize: 13,
    fontWeight: "600",
  },
  datePlaceholderText: {
    color: "rgba(58,35,23,0.35)",
    flex: 1,
    fontSize: 13,
    fontWeight: "600",
  },
  addStopButton: {
    alignItems: "center",
    backgroundColor: "#c9502e",
    borderRadius: 18,
    flexDirection: "row",
    gap: 8,
    height: 50,
    justifyContent: "center",
    marginTop: 18,
  },
  addStopButtonDisabled: {
    opacity: 0.5,
  },
  addStopButtonPressed: {
    backgroundColor: "#b5452a",
  },
  addStopButtonText: {
    color: "#fff8ea",
    fontSize: 16,
    fontWeight: "600",
  },
  stopCard: {
    backgroundColor: "#fdf8ee",
    borderRadius: 22,
    marginTop: 16,
    padding: 18,
  },
  stopTopRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
  },
  stopBadge: {
    alignItems: "center",
    backgroundColor: "#c9502e",
    borderRadius: 999,
    height: 26,
    justifyContent: "center",
    width: 26,
  },
  stopBadgeText: {
    color: "#fff8ea",
    fontSize: 13,
    fontWeight: "600",
  },
  stopLabel: {
    color: "#a68a6c",
    fontSize: 13,
    fontWeight: "600",
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  nightsText: {
    color: "#a68a6c",
    flex: 1,
    fontSize: 14,
    textAlign: "right",
  },
  stopDeleteButton: {
    alignItems: "center",
    backgroundColor: "#ecdec2",
    borderRadius: 999,
    height: 32,
    justifyContent: "center",
    width: 32,
  },
  stopCityRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
    marginTop: 14,
  },
  stopCityTextWrap: {
    flex: 1,
  },
  stopCity: {
    color: "#2d1b12",
    fontFamily: displayFontFamily,
    fontSize: 21,
    fontWeight: "600",
  },
  stopCountry: {
    color: "#a68a6c",
    fontSize: 14,
    marginTop: 1,
  },
  stopDivider: {
    backgroundColor: "#ecdec2",
    height: 1,
    marginTop: 14,
  },
  dateReadout: {
    flex: 1,
    marginTop: 0,
  },
  tipCard: {
    alignItems: "center",
    backgroundColor: "#f3ddb9",
    borderRadius: 20,
    flexDirection: "row",
    gap: 12,
    marginTop: 20,
    padding: 16,
  },
  tipText: {
    color: "#5a4632",
    flex: 1,
    fontSize: 14,
    lineHeight: 20,
  },
  footer: {
    backgroundColor: "#f7ecd9",
    paddingBottom: 12,
    paddingHorizontal: 20,
    paddingTop: 12,
  },
  continueButton: {
    alignItems: "center",
    backgroundColor: "#c9502e",
    borderRadius: 24,
    flexDirection: "row",
    gap: 10,
    height: 58,
    justifyContent: "center",
  },
  continueButtonDisabled: {
    opacity: 0.5,
  },
  continueButtonPressed: {
    backgroundColor: "#b5452a",
  },
  continueButtonText: {
    color: "#fff8ea",
    fontSize: 18,
    fontWeight: "600",
  },
  pickerBackdrop: {
    backgroundColor: "rgba(58,35,23,0.45)",
    flex: 1,
    justifyContent: "flex-end",
  },
  pickerSheet: {
    backgroundColor: "#fdf8ee",
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    paddingBottom: 24,
    paddingHorizontal: 24,
    paddingTop: 12,
  },
  pickerDoneButton: {
    alignItems: "center",
    backgroundColor: "#c9502e",
    borderRadius: 20,
    height: 52,
    justifyContent: "center",
    marginTop: 8,
  },
  pickerDoneText: {
    color: "#fff8ea",
    fontSize: 16,
    fontWeight: "600",
  },
});
