import { StyleSheet } from "react-native";

import { displayFontFamily } from "../../src/theme/typography";

export const styles = StyleSheet.create({
  safeArea: {
    backgroundColor: "#f7ecd9",
    flex: 1,
    minHeight: 0,
  },
  topRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 14,
    paddingHorizontal: 20,
    paddingTop: 12,
  },
  backButton: {
    alignItems: "center",
    backgroundColor: "#fdf8ee",
    borderColor: "#ecd7b4",
    borderRadius: 16,
    borderWidth: 1,
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  stepperRow: {
    flex: 1,
    flexDirection: "row",
    gap: 8,
  },
  stepperSegment: {
    backgroundColor: "#ecdcc0",
    borderRadius: 999,
    flex: 1,
    height: 5,
  },
  stepperSegmentActive: {
    backgroundColor: "#c9502e",
  },
  headerCopy: {
    paddingHorizontal: 20,
  },
  stepLabel: {
    color: "#d98a3d",
    fontSize: 13,
    fontWeight: "600",
    letterSpacing: 1.2,
    marginTop: 22,
    textTransform: "uppercase",
  },
  tripLabel: {
    color: "#e08b20",
    fontSize: 17,
    fontWeight: "600",
    letterSpacing: 1.8,
    textTransform: "uppercase",
  },
  title: {
    color: "#2d1b12",
    fontFamily: displayFontFamily,
    fontSize: 30,
    fontWeight: "600",
    marginTop: 6,
  },
  progressRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 14,
    paddingHorizontal: 20,
    paddingTop: 24,
  },
  progressTrack: {
    backgroundColor: "#eadbbf",
    borderRadius: 999,
    flex: 1,
    height: 9,
    overflow: "hidden",
  },
  progressFill: {
    backgroundColor: "#c9502e",
    borderRadius: 999,
    height: "100%",
  },
  progressText: {
    color: "#8b7a65",
    fontSize: 17,
    fontWeight: "600",
  },
  scrollView: {
    flex: 1,
    minHeight: 0,
  },
  scrollContent: {
    paddingBottom: 24,
    paddingHorizontal: 20,
    paddingTop: 28,
  },
  weatherSection: {
    backgroundColor: "#f5e3bf",
    borderColor: "#eccd8d",
    borderRadius: 24,
    borderWidth: 1,
    padding: 20,
  },
  weatherHeadingRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 16,
  },
  weatherBang: {
    color: "#c27a18",
    fontSize: 28,
    fontWeight: "600",
    width: 28,
    textAlign: "center",
  },
  weatherTitle: {
    color: "#5b421b",
    flex: 1,
    fontSize: 20,
    fontWeight: "600",
  },
  weatherIntro: {
    color: "#8b5f1f",
    fontSize: 16,
    lineHeight: 24,
    marginTop: 10,
  },
  weatherList: {
    gap: 14,
    marginTop: 20,
  },
  weatherItem: {
    alignItems: "center",
    backgroundColor: "#fffaf0",
    borderColor: "#ead7b7",
    borderRadius: 20,
    borderWidth: 1,
    flexDirection: "row",
    gap: 14,
    padding: 16,
  },
  weatherIconWrap: {
    alignItems: "center",
    backgroundColor: "#f4e2bd",
    borderRadius: 14,
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  itemTextWrap: {
    flex: 1,
  },
  itemLabel: {
    color: "#2d1b12",
    fontSize: 20,
    fontWeight: "600",
  },
  itemDetailRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 6,
    marginTop: 6,
  },
  itemDetail: {
    color: "#8b5f1f",
    flex: 1,
    fontSize: 15,
  },
  checkCircle: {
    alignItems: "center",
    borderColor: "#d6bf8f",
    borderRadius: 999,
    borderWidth: 3,
    height: 42,
    justifyContent: "center",
    width: 42,
  },
  checkCircleChecked: {
    backgroundColor: "#c9502e",
    borderColor: "#c9502e",
  },
  sectionWrap: {
    marginTop: 28,
  },
  sectionLabel: {
    color: "#8b7a65",
    fontSize: 18,
    fontWeight: "600",
    letterSpacing: 1.5,
    marginBottom: 14,
    marginLeft: 6,
    textTransform: "uppercase",
  },
  basicList: {
    backgroundColor: "#fffaf0",
    borderColor: "#ead7b7",
    borderRadius: 22,
    borderWidth: 1,
    overflow: "hidden",
  },
  basicItem: {
    alignItems: "center",
    borderBottomColor: "#eadfc7",
    borderBottomWidth: 1,
    flexDirection: "row",
    gap: 18,
    minHeight: 72,
    paddingHorizontal: 18,
  },
  basicItemText: {
    color: "#2d1b12",
    flex: 1,
    fontSize: 20,
  },
  addItemRow: {
    alignItems: "center",
    backgroundColor: "#fffaf0",
    borderColor: "#ead7b7",
    borderRadius: 20,
    borderWidth: 1,
    flexDirection: "row",
    gap: 10,
    minHeight: 74,
    paddingLeft: 18,
    paddingRight: 10,
  },
  addItemInput: {
    color: "#2d1b12",
    flex: 1,
    fontSize: 19,
    minHeight: 58,
  },
  addItemButton: {
    alignItems: "center",
    backgroundColor: "#c9502e",
    borderRadius: 16,
    height: 54,
    justifyContent: "center",
    width: 54,
  },
  helperText: {
    color: "#b1a187",
    fontSize: 16,
    lineHeight: 22,
    marginTop: 18,
    textAlign: "center",
  },
  footer: {
    backgroundColor: "#f7ecd9",
    paddingBottom: 12,
    paddingHorizontal: 20,
    paddingTop: 12,
  },
  saveButton: {
    alignItems: "center",
    backgroundColor: "#c9502e",
    borderRadius: 24,
    flexDirection: "row",
    gap: 12,
    height: 64,
    justifyContent: "center",
  },
  saveButtonPressed: {
    backgroundColor: "#b5452a",
  },
  saveButtonText: {
    color: "#fff8ea",
    fontSize: 20,
    fontWeight: "600",
  },
});
